### ISSUE TITLE
pypi

### ISSUE THREAD

**Issue by lfreeke** [steffex/pyPostcode#11]
Hey Stefan, 

I cannot find the pyPostcode 0.2 on https://pypi.python.org.
Do you still have to push this? 

cc @StefanRijnhart

**Comment by steffex** [comment]
@lfreeke I think that @StefanRijnhart didn't submit the update yet.

**Comment by StefanRijnhart** [comment]
@steffex give it a try yourself. It's very easy.

**Comment by steffex** [comment]
@lfreeke @StefanRijnhart i'll try to fix it during the week. Currently low on spare time.. :cry:

**Comment by lfreeke** [comment]
@steffex Any news on this?

**Comment by steffex** [comment]
@lfreeke just tried to update the package, but I can't. I can't access it with my account.

**Comment by StefanRijnhart** [comment]
@steffex Is your Pypi account linked to this email address? You should have access based on this property in the setup.cfg. https://github.com/steffex/pyPostcode/blob/master/setup.py#L8

**Comment by steffex** [comment]
@StefanRijnhart yes thats the exactly the same!

**Comment by StefanRijnhart** [comment]
OK, I've uploaded version 0.2 now. I also see that I can make you a co-owner of the Pypi package through the Pypi interface if you send me your Pypi user name. Sorry I missed that before.

**Comment by steffex** [comment]
@StefanRijnhart my username is "steffex"

**Comment by StefanRijnhart** [comment]
Thanks, added you as an owner the package. Do you see it when you log in
to Pypi?

**Comment by steffex** [comment]
Yup! :+1:
