### ISSUE TITLE
Make version 2 API as default

### ISSUE THREAD

**Issue by steffex** [steffex/pyPostcode#12]
Update in march when version 1 will be shutdown

**Comment by RoelAdriaans-B-informed** [comment]
New key currently is an api 2 key, version 1 api is no longer available .. 

{"message":"Version 1 of the Postcode API is not available anymore. More info: http:\/\/blog.apiwise.nl\/van-postcode-api-1-0-naar-2-0\/"} , see in Dutch http://blog.apiwise.nl/van-postcode-api-1-0-naar-2-0/

**Comment by steffex** [comment]
@RoelAdriaans-B-informed i've added a release to github. I'll add it to pypi later today

**Comment by steffex** [comment]
@RoelAdriaans-B-informed the package is updated on pypi! Sorry it took a while.
