### ISSUE TITLE
Limitations using "huisletter" and "toevoeging"

### ISSUE THREAD

**Issue by mdxs** [steffex/pyPostcode#7]
Perhaps an implementation issue in postcodeapi.nu itself, but I've not yet found how the API is to differentiate between "1185ZH/7/G" and "1185ZH/7/G/BIS" (see https://www.postcode.nl/1185ZH/7/G with 43m2 and https://www.postcode.nl/1185ZH/7/G%20BIS with 32m2)

Instead, the API seems to return (with "view=bag" added) in both cases the id="0362010002002946" VBO; which can be queried for via https://service1.kadaster.nl/bag/bag-burger/secured/selectie, using "Verblijfsobject" (VBO) and the id above... showing that it belongs to "1185ZH/7/A"

Looking at the (current) "bag-adressen-bagaveen.csv.gz" file downloaded from http://data.nlextract.nl/bag/csv/; it shows that "VBO 0362010002002951"="1185ZH/7/G" and "VBO 0362010002182896"="1185ZH/7/G/BIS"; which can be confirmed by above Kadaster search feature... and note how the m2 values match the postcode.nl checks.

To me it seems like postcodeapi.nu is (incorrectly) ignoring "huisletter" and "huisnummertoevoeging" when parsing the BAG extract (and I assume that they use similar files like the ones that can be obtained from http://data.nlextract.nl/bag/csv/ (maybe more directly from the source agencies). It appears that their implementation always returns the first "7" found (or perhaps imported?) and ignoring any further detailing.

Now, as said, this might be due to me not correctly reading the API documentation for this service at http://api.postcodeapi.nu/docs/resources/housenumber

**Comment by steffex** [comment]
@mdxs perhaps this will get fixed with the upcoming new version ([link](https://github.com/apiwise/postcodeapi) of the API.

With the new version on the way, I think they are not going to implement this feature. Thats why I'm closing this issue for now. If this becomes relevant again, I'll open it again.
